### ISSUE TITLE
Update for FW 15.0.0

### ISSUE THREAD

**Issue by IanRises** [Phalk/NX-Activity-Log-NPE#1]
after updating to 15.0.0 my activity is completely blank.. think this could be fixed? 
![IMG_1019](https://user-images.githubusercontent.com/15117113/197061825-04bca56d-b37e-4814-9c6c-91ef5d605ee2.jpg)

**Comment by Phalk** [comment]
Since this is just a branch from the original app, we'll have to wait until they fix it on the main branch so I can update this version too.

**Comment by Fluff663** [comment]
> 

https://github.com/zdm65477730/NX-Activity-Log/tree/develop

This is a working version as far as I can tell

**Comment by impeeza** [comment]
Still a Issue on FW 16.x

**Comment by Phalk** [comment]
Updated using zdm65477730's fork.
